
name: Java compile 

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        maven: [ '3.8.6' ]

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.5.1
        with:
          java-version: 19
          maven-version: ${{ matrix.maven }}

      - name: Maven clean
        run: mvn-clean-win.bat
        working-directory: egg_StackOverflow_73229247

      - name: Maven compile
        run: mvn-compile-win.bat
        working-directory: egg_StackOverflow_73229247
